run:
  timeout: 3m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - staticcheck
    - revive
    - gosimple
    - errcheck
    - ineffassign
    - gofmt
    - goimports
    - misspell
    - gocyclo

  disable-all: false
  fast: false

linters-settings:
  gocyclo:
    min-complexity: 15
  revive:
    ignore-generated-header: true

issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-use-default: false

exclude-rules:
  - path: "_test.go"
    linters:
      - gocyclo
  - path: "^migrations/"
    linters:
      - gofmt
      - goimports
      - gocyclo
